// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClaimChallengeReward(arg1) {
  return window['go']['main']['App']['ClaimChallengeReward'](arg1);
}

export function ClaimDailyReward() {
  return window['go']['main']['App']['ClaimDailyReward']();
}

export function ClaimWeeklyGoalReward(arg1) {
  return window['go']['main']['App']['ClaimWeeklyGoalReward'](arg1);
}

export function EquipItem(arg1) {
  return window['go']['main']['App']['EquipItem'](arg1);
}

export function GetAchievementCounts() {
  return window['go']['main']['App']['GetAchievementCounts']();
}

export function GetAchievements() {
  return window['go']['main']['App']['GetAchievements']();
}

export function GetActiveProject() {
  return window['go']['main']['App']['GetActiveProject']();
}

export function GetAvatar() {
  return window['go']['main']['App']['GetAvatar']();
}

export function GetDailyChallenges() {
  return window['go']['main']['App']['GetDailyChallenges']();
}

export function GetDailyLogin() {
  return window['go']['main']['App']['GetDailyLogin']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetEquipped() {
  return window['go']['main']['App']['GetEquipped']();
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetShopItems(arg1) {
  return window['go']['main']['App']['GetShopItems'](arg1);
}

export function GetSprintExplanations(arg1) {
  return window['go']['main']['App']['GetSprintExplanations'](arg1);
}

export function GetSprintHints(arg1) {
  return window['go']['main']['App']['GetSprintHints'](arg1);
}

export function GetSprintQuestions(arg1) {
  return window['go']['main']['App']['GetSprintQuestions'](arg1);
}

export function GetSprints() {
  return window['go']['main']['App']['GetSprints']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetWallet() {
  return window['go']['main']['App']['GetWallet']();
}

export function GetWeeklyGoals() {
  return window['go']['main']['App']['GetWeeklyGoals']();
}

export function PurchaseItem(arg1) {
  return window['go']['main']['App']['PurchaseItem'](arg1);
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function SetAvatarName(arg1) {
  return window['go']['main']['App']['SetAvatarName'](arg1);
}

export function SetCreatureType(arg1) {
  return window['go']['main']['App']['SetCreatureType'](arg1);
}

export function SubmitSprintAnswers(arg1, arg2) {
  return window['go']['main']['App']['SubmitSprintAnswers'](arg1, arg2);
}

export function UnequipSlot(arg1) {
  return window['go']['main']['App']['UnequipSlot'](arg1);
}
