// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string):Promise<void>;

export function ClaimChallengeReward(arg1:number):Promise<number>;

export function ClaimDailyReward():Promise<number>;

export function ClaimWeeklyGoalReward(arg1:number):Promise<number>;

export function GenerateExamForDomain(arg1:string):Promise<main.GenerationResultData>;

export function GenerateSprintForDomain(arg1:string,arg2:string):Promise<main.GenerationResultData>;

export function GetAchievementCounts():Promise<number|number>;

export function GetAchievements():Promise<Array<main.AchievementData>>;

export function GetActiveProject():Promise<main.ProjectData>;

export function GetAvatar():Promise<main.AvatarData>;

export function GetDailyChallenges():Promise<Array<main.ChallengeData>>;

export function GetDailyLogin():Promise<main.DailyLoginData>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetDomainAchievements(arg1:string):Promise<Array<main.DomainAchievementData>>;

export function GetDomains():Promise<Array<main.DomainData>>;

export function GetGenerationGate(arg1:string):Promise<main.GenerationGateData>;

export function GetHintPacks():Promise<Array<main.HintPackData>>;

export function GetHintTokenBalance():Promise<main.HintTokenData>;

export function GetKnowledgeBase():Promise<Array<main.KnowledgeQuestionData>>;

export function GetKnowledgeByDomain(arg1:string):Promise<Array<main.KnowledgeQuestionData>>;

export function GetOllamaConfig():Promise<main.OllamaConfigData>;

export function GetOllamaModels():Promise<Array<string>>;

export function GetProfile():Promise<main.ProfileData>;

export function GetProjects():Promise<Array<main.ProjectData>>;

export function GetPullProgress():Promise<main.PullProgressData>;

export function GetQuestionSpeechText(arg1:number,arg2:number):Promise<string>;

export function GetSprintExplanations(arg1:number):Promise<Array<string>>;

export function GetSprintHints(arg1:number):Promise<Array<string>>;

export function GetSprintQuestions(arg1:number):Promise<Array<main.QuestionData>>;

export function GetSprints():Promise<Array<main.SprintData>>;

export function GetStats(arg1:string):Promise<Array<main.DailyStatsData>>;

export function GetSystemInfo():Promise<main.SystemInfoData>;

export function GetUsedHintsForSprint(arg1:number):Promise<Array<number>>;

export function GetWallet():Promise<main.WalletData>;

export function GetWeeklyGoals():Promise<Array<main.WeeklyGoalData>>;

export function IsOllamaAvailable():Promise<boolean>;

export function IsPiperAvailable():Promise<boolean>;

export function PullOllamaModel(arg1:string):Promise<void>;

export function PurchaseHintTokens(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function ScanAndImportExams(arg1:string):Promise<string>;

export function SetActiveProject(arg1:string):Promise<void>;

export function SetAvatarName(arg1:string):Promise<void>;

export function SetCreatureType(arg1:string):Promise<void>;

export function SpeakQuestion(arg1:number,arg2:number):Promise<void>;

export function SpeakSprintResult(arg1:boolean,arg2:number,arg3:number):Promise<void>;

export function SpeakText(arg1:string):Promise<void>;

export function SpeakTextBlocking(arg1:string):Promise<void>;

export function StopSpeech():Promise<void>;

export function SubmitSprintAnswers(arg1:number,arg2:Array<string>):Promise<main.SprintResultData>;

export function TestOllamaConnection():Promise<main.TestResultData>;

export function UpdateOllamaConfig(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function UseHintToken(arg1:number,arg2:number):Promise<string>;
