// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string):Promise<void>;

export function ClaimChallengeReward(arg1:number):Promise<number>;

export function ClaimDailyReward():Promise<number>;

export function ClaimWeeklyGoalReward(arg1:number):Promise<number>;

export function EquipItem(arg1:string):Promise<void>;

export function GetAchievementCounts():Promise<number|number>;

export function GetAchievements():Promise<Array<main.AchievementData>>;

export function GetActiveProject():Promise<main.ProjectData>;

export function GetAvatar():Promise<main.AvatarData>;

export function GetDailyChallenges():Promise<Array<main.ChallengeData>>;

export function GetDailyLogin():Promise<main.DailyLoginData>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetDomainAchievements(arg1:string):Promise<Array<main.DomainAchievementData>>;

export function GetDomains():Promise<Array<main.DomainData>>;

export function GetEquipped():Promise<main.EquippedData>;

export function GetInventory():Promise<Array<main.ShopItemData>>;

export function GetProfile():Promise<main.ProfileData>;

export function GetProjects():Promise<Array<main.ProjectData>>;

export function GetShopItems(arg1:string):Promise<Array<main.ShopItemData>>;

export function GetSprintExplanations(arg1:number):Promise<Array<string>>;

export function GetSprintHints(arg1:number):Promise<Array<string>>;

export function GetSprintQuestions(arg1:number):Promise<Array<main.QuestionData>>;

export function GetSprints():Promise<Array<main.SprintData>>;

export function GetStats(arg1:string):Promise<Array<main.DailyStatsData>>;

export function GetWallet():Promise<main.WalletData>;

export function GetWeeklyGoals():Promise<Array<main.WeeklyGoalData>>;

export function PurchaseItem(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function ScanAndImportExams(arg1:string):Promise<string>;

export function SetActiveProject(arg1:string):Promise<void>;

export function SetAvatarName(arg1:string):Promise<void>;

export function SetCreatureType(arg1:string):Promise<void>;

export function SubmitSprintAnswers(arg1:number,arg2:Array<string>):Promise<main.SprintResultData>;

export function UnequipSlot(arg1:string):Promise<void>;
